export const unstable_instant = { prefetch: 'static' };

import { Settings, User, Bot, Key, Shield, MessageSquare, Save, Zap } from "lucide-react";

export default function SettingsPage() {
  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-white mb-2 flex items-center gap-3">
          <Settings className="w-8 h-8 text-slate-400" />
          Settings & AI Persona
        </h1>
        <p className="text-slate-400">Configure your brand voice, networking rules, and API connections.</p>
      </div>

      <div className="space-y-6">
        {/* Section 1: AI Persona */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-8">
          <h2 className="text-xl font-bold text-white mb-6 flex items-center gap-2">
            <Bot className="w-5 h-5 text-cyan-400" />
            AI Content Persona
          </h2>
          <div className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">Display Name</label>
                <input 
                  type="text" 
                  defaultValue="Ahad's Logos Engine"
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg p-3 text-white focus:outline-none focus:ring-2 focus:ring-cyan-500/50"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">Brand Voice Style</label>
                <select className="w-full bg-slate-950 border border-slate-800 rounded-lg p-3 text-white focus:outline-none focus:ring-2 focus:ring-cyan-500/50 appearance-none">
                  <option>Stoic & Technical</option>
                  <option>Aggressive & Bold</option>
                  <option>Empathetic & Nurturing</option>
                  <option>Direct Value Propositions</option>
                </select>
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-300 mb-2">Brand Biography (AI Context)</label>
              <textarea 
                rows={4}
                className="w-full bg-slate-950 border border-slate-800 rounded-lg p-3 text-white focus:outline-none focus:ring-2 focus:ring-cyan-500/50 resize-none"
                defaultValue="I am a software architect who blends technical depth with philosophical insights from Stoicism and Existentialism. I focus on B2B SaaS and developer productivity."
              />
              <p className="mt-2 text-xs text-slate-500">This context is used to fine-tune every post and message generated by Connexa.</p>
            </div>
          </div>
        </div>

        {/* Section 2: API & Integrations */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-8">
          <h2 className="text-xl font-bold text-white mb-6 flex items-center gap-2">
            <Key className="w-5 h-5 text-purple-400" />
            API & Integrations
          </h2>
          <div className="space-y-4">
            <div className="flex items-center justify-between p-4 bg-slate-950 border border-slate-800 rounded-lg">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-slate-800 rounded text-cyan-400">
                  <Zap className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="font-semibold text-white text-sm">Ollama Local Engine</h4>
                  <p className="text-xs text-slate-500">Endpoint: http://localhost:11434/v1</p>
                </div>
              </div>
              <button className="text-xs font-bold text-slate-400 hover:text-white transition-colors">Configure Model</button>
            </div>
            <div className="flex items-center justify-between p-4 bg-slate-950 border border-slate-800 rounded-lg">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-slate-800 rounded text-blue-500">
                  <Shield className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="font-semibold text-white text-sm">Facebook Page Integration</h4>
                  <p className="text-xs text-slate-500">Disconnected</p>
                </div>
              </div>
              <button className="text-xs font-bold text-cyan-400 hover:text-cyan-300 transition-colors">Connect Page</button>
            </div>
          </div>
        </div>

        {/* Section 3: Safety Controls */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-8">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <Shield className="w-5 h-5 text-emerald-400" />
              Safety & Automation Rules
            </h2>
            <div className="flex items-center gap-2">
               <span className="text-xs text-slate-400">Auto-Approve Messages</span>
               <div className="w-10 h-5 bg-cyan-600 rounded-full relative cursor-pointer">
                  <div className="absolute right-0.5 top-0.5 w-4 h-4 bg-white rounded-full shadow-sm" />
               </div>
            </div>
          </div>
          <div className="space-y-4">
             <div className="flex items-center gap-3 p-4 bg-emerald-500/5 border border-emerald-500/20 rounded-lg">
                <Shield className="w-5 h-5 text-emerald-400" />
                <p className="text-sm text-slate-300">"Human in the loop" is active. No automated networking requests will be sent without your final review.</p>
             </div>
          </div>
        </div>

        <div className="flex justify-end gap-3 pt-4">
          <button className="px-6 py-2.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg font-medium transition-colors">Discard</button>
          <button className="px-6 py-2.5 bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white rounded-lg font-bold shadow-lg transition-all flex items-center gap-2">
            <Save className="w-4 h-4" /> Save Configuration
          </button>
        </div>
      </div>
    </div>
  );
}
